/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    weine: Weine;
    events: Event;
    verleih: Verleih;
    media: Media;
    dokumente: Dokumente;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    weine: WeineSelect<false> | WeineSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    verleih: VerleihSelect<false> | VerleihSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    dokumente: DokumenteSelect<false> | DokumenteSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    kontakt: Kontakt;
  };
  globalsSelect: {
    kontakt: KontaktSelect<false> | KontaktSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Alle Weine, die auf der Website erscheinen. Die Reihenfolge lässt sich per Ziehen ändern.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weine".
 */
export interface Weine {
  id: number;
  _order?: string | null;
  /**
   * z. B. „Riesling trocken“
   */
  name: string;
  weinart: 'weisswein' | 'rotwein' | 'rose' | 'sekt' | 'sonstiges';
  jahrgang?: number | null;
  rebsorte?: string | null;
  /**
   * Geschmack, Charakter, passende Anlässe – der Text erscheint auf der Website.
   */
  beschreibung?: string | null;
  /**
   * z. B. 9.50
   */
  preis?: number | null;
  flaschengroesse?: string | null;
  /**
   * Foto der Weinflasche. Kann jederzeit ausgetauscht werden.
   */
  bild?: (number | null) | Media;
  /**
   * Wenn aktiviert, wird der Wein auf der Website als ausverkauft angezeigt.
   */
  ausverkauft?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Alle Bilder der Website – z. B. Weinflaschen, Event-Fotos und Verleih-Artikel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Kurze Beschreibung des Bildes, z. B. „Flasche Riesling 2024“. Wichtig für Google und Menschen mit Sehbehinderung.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Veranstaltungen wie Weinproben, Feste oder Führungen. Vergangene Events werden auf der Website automatisch ausgeblendet.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  /**
   * z. B. „Weinprobe im Gewölbekeller“
   */
  titel: string;
  datum: string;
  /**
   * z. B. „Weingut, Hauptstraße 1“
   */
  ort?: string | null;
  /**
   * Alle Details zum Event – Ablauf, was dabei ist, für wen es gedacht ist.
   */
  beschreibung?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Freier Text, z. B. „25 € pro Person“ oder „Eintritt frei“.
   */
  preis?: string | null;
  bild?: (number | null) | Media;
  /**
   * Optional: Programm, Einladung oder Anmeldeformular als PDF.
   */
  pdf?: (number | null) | Dokumente;
  /**
   * Optional: Link zur Anmeldung, z. B. ein Formular oder eine E-Mail-Adresse.
   */
  anmeldeLink?: string | null;
  /**
   * Wenn aktiviert, wird das Event auf der Website als ausgebucht markiert.
   */
  ausgebucht?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * PDF-Dateien, z. B. Event-Programme, Weinkarten oder Preislisten.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dokumente".
 */
export interface Dokumente {
  id: number;
  /**
   * Name des Dokuments, z. B. „Programm Weinfest 2026“.
   */
  titel: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Ausschankwagen, Technik und weitere Artikel zum Ausleihen. Die Reihenfolge lässt sich per Ziehen ändern.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verleih".
 */
export interface Verleih {
  id: number;
  _order?: string | null;
  /**
   * z. B. „Ausschankwagen“
   */
  name: string;
  kategorie?: ('ausschank' | 'technik' | 'mobiliar' | 'sonstiges') | null;
  /**
   * Was ist es, was ist enthalten, wofür eignet es sich?
   */
  beschreibung?: string | null;
  /**
   * Freier Text, z. B. „50 € pro Tag“ oder „Preis auf Anfrage“.
   */
  preisInfo?: string | null;
  /**
   * Ein oder mehrere Fotos des Artikels.
   */
  bilder?: (number | Media)[] | null;
  /**
   * Wenn deaktiviert, wird der Artikel als derzeit nicht verfügbar angezeigt.
   */
  verfuegbar?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'weine';
        value: number | Weine;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'verleih';
        value: number | Verleih;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'dokumente';
        value: number | Dokumente;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weine_select".
 */
export interface WeineSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  weinart?: T;
  jahrgang?: T;
  rebsorte?: T;
  beschreibung?: T;
  preis?: T;
  flaschengroesse?: T;
  bild?: T;
  ausverkauft?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  titel?: T;
  datum?: T;
  ort?: T;
  beschreibung?: T;
  preis?: T;
  bild?: T;
  pdf?: T;
  anmeldeLink?: T;
  ausgebucht?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verleih_select".
 */
export interface VerleihSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  kategorie?: T;
  beschreibung?: T;
  preisInfo?: T;
  bilder?: T;
  verfuegbar?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dokumente_select".
 */
export interface DokumenteSelect<T extends boolean = true> {
  titel?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Kontaktdaten, die auf der Website angezeigt werden (z. B. im Footer).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kontakt".
 */
export interface Kontakt {
  id: number;
  /**
   * z. B. „Weingut Multeau“
   */
  name?: string | null;
  adresse?: string | null;
  telefon?: string | null;
  email?: string | null;
  /**
   * Freier Text, z. B. „Fr 15–18 Uhr, Sa 10–16 Uhr und nach Vereinbarung“.
   */
  oeffnungszeiten?: string | null;
  instagram?: string | null;
  facebook?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kontakt_select".
 */
export interface KontaktSelect<T extends boolean = true> {
  name?: T;
  adresse?: T;
  telefon?: T;
  email?: T;
  oeffnungszeiten?: T;
  instagram?: T;
  facebook?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}